Remove inbox benchmark.
This is making cros perf bot fails.

Clearly, the credential file for cros doesn't exist anymore:

$./depot_tools/gsutil.py ls gs://chromium-telemetry/01ff3ee8b3e06ade7f96bdef52b528422e71251e
CommandException: No such object gs://chromium-telemetry/01ff3ee8b3e06ade7f96bdef52b528422e71251e

Review URL: https://codereview.chromium.org/1232463004

Cr-Commit-Position: refs/heads/master@{#338939}
NOKEYCHECK=True
GitOrigin-RevId: 52511e46ac0f0c38f6c59a73b8a7c30fe014805f