[tools/perf] Use six.ensure_str() if available.
Skylab bots in ChromeOS are missing vpython environment and have
outdated python modules. six doesn't have ensure_str() causing:
"AttributeError: 'module' object has no attribute 'ensure_str'".

Use ensure_str() only if it is available. This is a temporary solution
for b/206008069 to unblock b/205303357.

Change-Id: I1a5012f22479889fa002d3d3106ac26915c3cec9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3296396
Commit-Queue: Denis Nikitin <denik@chromium.org>
Reviewed-by: John Chen <johnchen@chromium.org>
Cr-Commit-Position: refs/heads/main@{#944396}
NOKEYCHECK=True
GitOrigin-RevId: c188c550c0d766ea2ba00dee0ec374d3c25ba183