[Telemetry] Fix imports for generate_system_health_csv
My recent changes to add StoryExpectations broke a tool. By adding an import this problem can be resolved.

Traceback (most recent call last):
  <module> at
/usr/local/google/code/clankium/src/tools/perf/generate_system_health_csv:13
    import page_sets
  <module> at
/usr/local/google/code/clankium/src/tools/perf/page_sets/__init__.py:18
    base_classes = [story.StorySet, story.expectations.StoryExpectations]
AttributeError: 'module' object has no attribute 'expectations'

BUG=723783

Review-Url: https://codereview.chromium.org/2898013002
Cr-Commit-Position: refs/heads/master@{#473628}
NOKEYCHECK=True
GitOrigin-RevId: 67c4adc7f2a3ed20b86a7235df43d33c160aa0d9