Revert of Reenable smoothness.tough_animation_cases perf benchmark on Android (https://codereview.chromium.org/358963005/)
Reason for revert:
Still broken on all android bots.

e.g.
http://chromegw/i/chromium.perf/builders/Android%20Nexus10%20Perf/builds/2021/steps/smoothness.tough_animation_cases/logs/stdio

Failure while running http://ie.microsoft.com/testdrive/performance/robohornetpro/

NotEnoughFramesError: Only 0 frame timestamps were collected (at least two are required).
Issues that have caused this in the past:
- Browser bugs that prevents the page from redrawing
- Bugs in the synthetic gesture code
- Page and benchmark out of sync (e.g. clicked element was renamed)
- Pages that render extremely slow
- Pages that can't be scrolled

Original issue's description:
> Reenable smoothness.tough_animation_cases perf benchmark on Android
>
> BUG=350692
>
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=281221

TBR=dtu@chromium.org,alancutter@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=350692

Review URL: https://codereview.chromium.org/367943005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@281539 0039d316-1c4b-4281-b951-d872f2087c98
NOKEYCHECK=True
GitOrigin-RevId: c01d3c2efe15f8c881c0314481f937b16703bff1