Revert of Revert of [Telemtry] Move url lists of alexa1-10000 page to a json file. (patchset #1 id:1 of https://codereview.chromium.org/920953003/)
Reason for revert:
Original CL was ok. Failures were most likely due to https://codereview.chromium.org/914303007/ instead.

Original issue's description:
> Revert of [Telemtry] Move url lists of alexa1-10000 page to a json file. (patchset #1 id:1 of https://codereview.chromium.org/915303002/)
>
> Reason for revert:
> Build broke on many bots:
>
> Example:
> https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%281%29/builds/36194
>
> Running ['E:\\b\\depot_tools\\python276_bin\\python.exe', u'E:\\b\\build\\scripts\\tools\\runit.py', '--show-path', 'E:\\b\\depot_tools\\python276_bin\\python.exe', u'E:\\b\\build\\scripts\\slave\\runtest.py', '--target', 'Release', '--xvfb', '--builder-name', u'Win7 Tests (1)', '--slave-name', u'vm801-m1', '--build-number', '36194', '--build-properties', '{"buildnumber": 36194, "slavename": "vm801-m1", "buildername": "Win7 Tests (1)"}', '--annotate', 'gtest', '--test-type', 'telemetry_unittests', '--run-python-script', 'E:\\b\\build\\slave\\Win7_Tests__1_\\build\\src\\tools\\telemetry\\run_tests', '--browser', 'release', '--retry-limit', '3', '--write-full-results-to', 'c:\\users\\chrome~2\\appdata\\local\\temp\\tmpo3eir6']
> Set PYTHONPATH: E:\b\build\..\build_internal\site_config;E:\b\build\third_party\httplib2\python2;E:\b\build\third_party\zope;E:\b\build\third_party\uritemplate;E:\b\build\third_party\twisted_8_1;E:\b\build\third_party\tempita_0_5;E:\b\build\third_party\swarm_client;E:\b\build\third_party\sqlalchemy_migrate_0_7_1;E:\b\build\third_party\sqlalchemy_0_7_1;E:\b\build\third_party\simplejson;E:\b\build\third_party\setuptools-0.6c11;E:\b\build\third_party\pytz;E:\b\build\third_party\psutils;E:\b\build\third_party\oauth2client;E:\b\build\third_party\mock-1.0.1;E:\b\build\third_party\mock-0.7.2;E:\b\build\third_party\mock-0.6.0;E:\b\build\third_party\markupsafe;E:\b\build\third_party\lighttpd;E:\b\build\third_party\jinja2;E:\b\build\third_party\infra;E:\b\build\third_party\httplib2;E:\b\build\third_party\gsutil;E:\b\build\third_party\google_api_python_client;E:\b\build\third_party\depot_tools_patch;E:\b\build\third_party\depot_tools;E:\b\build\third_party\decorator_3_3_1;E:\b\build\third_party\Crypto;E:\b\build\third_party\coverage-3.7.1;E:\b\build\third_party\cherrypy;E:\b\build\third_party\buildbot_8_4p1;E:\b\build\third_party\buildbot_7_12;E:\b\build\third_party\.svn;E:\b\build\site_config;E:\b\build\scripts;E:\b\build\scripts\release;E:\b\build\third_party;E:\b\build\third_party\requests_1_2_3;E:\b\build_internal\site_config;E:\b\build_internal\symsrc;E:\b\build\slave;E:\b\build\third_party\buildbot_slave_8_4;E:\b\build\third_party\twisted_10_2;
>   File "E:\b\depot_tools\python276_bin\python.exe", line 1
> SyntaxError: Non-ASCII character '\x90' in file E:\b\depot_tools\python276_bin\python.exe on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
> Command ['E:\\b\\depot_tools\\python276_bin\\python.exe', u'E:\\b\\build\\scripts\\tools\\runit.py', '--show-path', 'E:\\b\\depot_tools\\python276_bin\\python.exe', u'E:\\b\\build\\scripts\\slave\\runtest.py', '--target', 'Release', '--xvfb', '--builder-name', u'Win7 Tests (1)', '--slave-name', u'vm801-m1', '--build-number', '36194', '--build-properties', '{"buildnumber": 36194, "slavename": "vm801-m1", "buildername": "Win7 Tests (1)"}', '--annotate', 'gtest', '--test-type', 'telemetry_unittests', '--run-python-script', 'E:\\b\\build\\slave\\Win7_Tests__1_\\build\\src\\tools\\telemetry\\run_tests', '--browser', 'release', '--retry-limit', '3', '--write-full-results-to', 'c:\\users\\chrome~2\\appdata\\local\\temp\\tmpo3eir6'] returned exit code 1
> Traceback (most recent call last):
>   File "E:\b\build\slave\Win7_Tests__1_\build\src\testing\scripts\telemetry_unittests.py", line 54, in <module>
>     sys.exit(common.run_script(sys.argv[1:], funcs))
>   File "E:\b\build\slave\Win7_Tests__1_\build\src\testing\scripts\common.py", line 49, in run_script
>     return args.func(args)
>   File "E:\b\build\slave\Win7_Tests__1_\build\src\testing\scripts\telemetry_unittests.py", line 31, in main_run
>     results = json.load(f)
>   File "E:\b\depot_tools\python276_bin\lib\json\__init__.py", line 290, in load
>
> @@@STEP_CURSOR telemetry_unittests@@@
>
> Original issue's description:
> > [Telemtry] Move url lists of alexa1-10000 page to a json file.
> >
> > Existing implementation of alexa1-10000 embeds the huge url list in
> > the python file, which is a terrible. It makes it super hard to navigate
> > through the file, or review its content, and make it harder to update the
> > alexa1-10000 pages if needed.
> >
> > Committed: https://crrev.com/fec4b0793f9d7eb6bef66f83687f10e6391dff62
> > Cr-Commit-Position: refs/heads/master@{#316012}
>
> TBR=sullivan@chromium.org,dtu@chromium.org,nednguyen@google.com
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
>
> Committed: https://crrev.com/c0cee90848513819e5a80c38f0337e56f611e02f
> Cr-Commit-Position: refs/heads/master@{#316049}

TBR=sullivan@chromium.org,dtu@chromium.org,nednguyen@google.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/924513004

Cr-Commit-Position: refs/heads/master@{#316055}
NOKEYCHECK=True
GitOrigin-RevId: af25c16d0200267abc6ec697cec05eddbdd3ab9c